apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:

  # trigger: when to send the webhook
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded', 'Failed', 'Error'] and app.status.health.status in ['Healthy', 'Degraded']
      send: [cd-visibility-template]

  service.webhook.cd-vis-webhook: |
    url: https://webhook-intake.datad0g.com/api/v2/webhook
    headers:
    - name: "DD-CD-PROVIDER-ARGOCD"
      value: "true"
    - name: "DD-API-KEY"
      value: $dd-api-key
    - name: "Content-Type"
      value: "application/json"

  template.cd-visibility-template: |
    webhook:
      cd-vis-webhook:
        method: POST
        body: |
            {
              "app": {{toJson .app}},
              "context": {{toJson .context}},
              "service_type": {{toJson .serviceType}},
              "recipient": {{toJson .recipient}},
              "commit_metadata": {{toJson (call .repo.GetCommitMetadata .app.status.operationState.syncResult.revision)}}
            }
